export { StudentProfilePage } from './StudentProfilePage'
export { StudentLessonsPage } from './StudentLessonsPage'
export { StudentHomeworkPage } from './StudentHomeworkPage'
export { StudentPaymentsPage } from './StudentPaymentsPage'
export { StudentMaterialsPage } from './StudentMaterialsPage'
export { StudentTestsPage } from './StudentTestsPage'
